'use strict';(function(){(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpVersion='https://quantcast.mgr.consensu.org/tcfv2/cmp2.js';cmpScriptElement.src=cmpVersion;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #368bd6 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['bg','cs','da','de','el','en','es','et','fi','fr','ga','hr','hu','it','lt','lv','mt','nl','pl','pt','ro','sk','sl','sv'];return langs.indexOf(lang)===-1?false:true;};if(isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{'premiumProperties':{},'coreUiLabels':{},'premiumUiLabels':{},'coreConfig':{'quantcastAccountId':'LttNBH90ksWBW','privacyMode':["GDPR"],'hashCode':'M+2lNC3acIJyI3LDcAO9UQ','publisherCountryCode':'ES','initScreenBodyTextOption':1,'consentScope':'global','lang_':'en','displayUi':'always','initScreenRejectButtonShowing':false,'publisherLogo':'https://recetasdecocina.elmundo.es/wp-content/uploads/2020/01/logo_sergio_cuadrado_2-1.png','publisherName':'Recetas de cocina','publisherPurposeIds':[1,2,3,4,5,6,7,8,9,10],'publisherSpecialFeaturesIds':[1,2],'stacks':[42,1],'softOptInEnabled':false,'uiLayout':'popup','vendorListUpdateFreq':30,'thirdPartyStorageType':'iframe','showSummaryView':true,}});})();